--- #YAML:1.0
name:                Net-ADNS
version:             0.02
abstract:            Perl wrapper for the Asynchronous DNS client library
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Test::More:                    
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Salvador Fandino <sfandino@yahoo.com>
